[package]
name = "search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "search"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
walkdir = "2.3.2"
rust_search = "2.0.0"